### ISSUE TITLE
Regelbuch: Bei Proben Modifikator als SL manuell festlegen

### ISSUE THREAD

**Issue by vt-tom** [tyr0mancer/dsa5-meistertools#4]
Ich fände es besser, wenn der Modifikator im Fenster Regelbuch vorgeschlagen aber veränderbar ist. Dem Spieler das in den Chat zu posten und dann zu sagen, mach aber aus der 3 eine 1 wegen schlechtem Wetter finde ich irgendwie nicht ergonomisch.

**Comment by tyr0mancer** [comment]
Ist so geplant. Außerdem Einbeziehung der Antwort aus dem Chat, also dem Wurfergebnis. falls eine Probe mehrere Würfe in Kette erfordert.

**Comment by tyr0mancer** [comment]
included in v 0.6.0
