### ISSUE TITLE
[Szenewechsel] - Karte politisch - Token Heldengruppe nicht als Actor vorhanden.

### ISSUE THREAD

**Issue by vt-tom** [tyr0mancer/dsa5-meistertools#5]
Ich weiß nicht ob das beabsichtigt ist, aber wenn die politische Karte importiert wird, ist ein Token der Gruppe auf der Map, aber ohne Actor. Wenn Absicht, kann das meinetwegen auch so bleiben, braucht aber ne Erklärung.

**Comment by tyr0mancer** [comment]
Ist ein Bug bzw eine unsaubere Karte. Wird mit dem nächsten Update wieder sauber

**Comment by tyr0mancer** [comment]
fixed with v0.6.0
